// @generated by tools/gen_from_registry.py --emit-jit — DO NOT EDIT BY HAND
// Regenerate: python3 tools/gen_from_registry.py --emit-jit
// Source of truth: pylib/jit_mappings.txt

use inkwell::execution_engine::ExecutionEngine;
use inkwell::module::Module;

/// Every LLVM name that JIT mode resolves to a Rust host function.
///
/// This is also the *authority* for the `--jit` preflight diagnostic: outside of
/// these names and the `vec_*` monomorphs, an external only resolves if the
/// compiler process itself already exports it — see `jit.rs::jit_symbol_resolvable`.
///
/// Host entries stay `*const ()`: a pointer has no integer value in const eval, so
/// the cast to the address `add_global_mapping` wants happens at run time.
pub const JIT_MAPPINGS: &[(&str, *const ())] = &[
    ("free", crate::runtime::std::std_free as *const ()),
    ("host_str_strip", crate::runtime::host::host_str_strip as *const ()),
    ("channel_send", crate::runtime::actor::channel::host_channel_send as *const ()),
    ("channel_recv", crate::runtime::actor::channel::host_channel_recv as *const ()),
    ("host_mpsc_channel", crate::runtime::actor::channel::host_mpsc_channel as *const ()),
    ("host_mpsc_send", crate::runtime::actor::channel::host_mpsc_send as *const ()),
    ("host_mpsc_recv", crate::runtime::actor::channel::host_mpsc_recv as *const ()),
    ("host_mpsc_try_recv", crate::runtime::actor::channel::host_mpsc_try_recv as *const ()),
    ("create_waker", crate::runtime::reactor::waker_create as *const ()),
    ("wake_waker", crate::runtime::reactor::waker_wake as *const ()),
    ("http_get", crate::runtime::host::host_http_get as *const ()),
    ("tls_handshake", crate::runtime::host::host_tls_handshake as *const ()),
    ("scheduler::init_runtime", crate::runtime::actor::scheduler::init_runtime as *const ()),
    ("future_poll_alloc", crate::runtime::host::future_poll_alloc as *const ()),
    ("future_poll_free", crate::runtime::host::future_poll_free as *const ()),
    ("future_state_get", crate::runtime::host::future_state_get as *const ()),
    ("future_state_set", crate::runtime::host::future_state_set as *const ()),
    ("future_poll", crate::runtime::host::future_poll as *const ()),
    ("future_result", crate::runtime::host::future_result as *const ()),
    ("future_ready", crate::runtime::host::future_ready as *const ()),
    ("zeta_array_set_bool", crate::runtime::zeta_runtime::zeta_array_set_bool as *const ()),
    ("zeta_print_i64", crate::runtime::zeta_runtime::zeta_print_i64 as *const ()),
    ("zeta_println_i64", crate::runtime::zeta_runtime::zeta_println_i64 as *const ()),
    ("println", crate::runtime::io::println as *const ()),
    ("println_bool", crate::runtime::io::println_bool as *const ()),
    ("vec_pop", crate::runtime::vec::zeta_vec_pop as *const ()),
    ("vec_set", crate::runtime::vec::zeta_vec_set as *const ()),
    ("vec_capacity", crate::runtime::vec::zeta_vec_capacity as *const ()),
    ("vec_clear", crate::runtime::vec::zeta_vec_clear as *const ()),
    ("fs_read_to_string", crate::runtime::fs::fs_read_to_string as *const ()),
    ("fs_write", crate::runtime::fs::fs_write as *const ()),
    ("fs_create_dir", crate::runtime::fs::fs_create_dir as *const ()),
    ("fs_create_dir_all", crate::runtime::fs::fs_create_dir_all as *const ()),
    ("fs_remove_file", crate::runtime::fs::fs_remove_file as *const ()),
    ("fs_remove_dir", crate::runtime::fs::fs_remove_dir as *const ()),
    ("fs_rename", crate::runtime::fs::fs_rename as *const ()),
    ("fs_copy", crate::runtime::fs::fs_copy as *const ()),
    ("fs_exists", crate::runtime::fs::fs_exists as *const ()),
    ("fs_is_file", crate::runtime::fs::fs_is_file as *const ()),
    ("fs_is_dir", crate::runtime::fs::fs_is_dir as *const ()),
    ("fs_metadata_len", crate::runtime::fs::fs_metadata_len as *const ()),
    ("fs_read_dir", crate::runtime::fs::fs_read_dir as *const ()),
    ("fs_canonicalize", crate::runtime::fs::fs_canonicalize as *const ()),
    ("path_parent", crate::runtime::path::path_parent as *const ()),
    ("path_file_name", crate::runtime::path::path_file_name as *const ()),
    ("path_extension", crate::runtime::path::path_extension as *const ()),
    ("path_join", crate::runtime::path::path_join as *const ()),
    ("path_is_absolute", crate::runtime::path::path_is_absolute as *const ()),
    ("path_as_str", crate::runtime::path::path_as_str as *const ()),
    ("tcp_connect", crate::runtime::net::tcp_connect as *const ()),
    ("tcp_write", crate::runtime::net::tcp_write as *const ()),
    ("tcp_read", crate::runtime::net::tcp_read as *const ()),
    ("tcp_close", crate::runtime::net::tcp_close as *const ()),
    ("tcp_bind", crate::runtime::net::tcp_bind as *const ()),
    ("tcp_accept", crate::runtime::net::tcp_accept as *const ()),
    ("host_str_all_interfaces", crate::runtime::host::host_str_all_interfaces as *const ()),
    ("atomic_bool_new", crate::runtime::atomic::atomic_bool_new as *const ()),
    ("atomic_bool_load", crate::runtime::atomic::atomic_bool_load as *const ()),
    ("atomic_bool_store", crate::runtime::atomic::atomic_bool_store as *const ()),
    ("atomic_i64_new", crate::runtime::atomic::atomic_i64_new as *const ()),
    ("atomic_i64_load", crate::runtime::atomic::atomic_i64_load as *const ()),
    ("atomic_i64_store", crate::runtime::atomic::atomic_i64_store as *const ()),
    ("atomic_i64_swap", crate::runtime::atomic::atomic_i64_swap as *const ()),
    ("atomic_i64_cas", crate::runtime::atomic::atomic_i64_cas as *const ()),
    ("atomic_i64_add", crate::runtime::atomic::atomic_i64_fetch_add as *const ()),
    ("atomic_i64_sub", crate::runtime::atomic::atomic_i64_fetch_sub as *const ()),
    ("char_is_digit", crate::runtime::char_::char_is_digit as *const ()),
    ("char_is_alphabetic", crate::runtime::char_::char_is_alphabetic as *const ()),
    ("char_is_alphanumeric", crate::runtime::char_::char_is_alphanumeric as *const ()),
    ("char_is_lowercase", crate::runtime::char_::char_is_lowercase as *const ()),
    ("char_is_uppercase", crate::runtime::char_::char_is_uppercase as *const ()),
    ("char_is_whitespace", crate::runtime::char_::char_is_whitespace as *const ()),
    ("char_to_lowercase", crate::runtime::char_::char_to_lowercase as *const ()),
    ("char_to_uppercase", crate::runtime::char_::char_to_uppercase as *const ()),
    ("char_from_u32", crate::runtime::char_::char_from_u32 as *const ()),
    ("char_to_digit", crate::runtime::char_::char_to_digit as *const ()),
    ("char_is_control", crate::runtime::char_::char_is_control as *const ()),
    ("char_is_numeric", crate::runtime::char_::char_is_numeric as *const ()),
    ("duration_add", crate::runtime::duration::duration_add as *const ()),
    ("duration_sub", crate::runtime::duration::duration_sub as *const ()),
    ("duration_mul", crate::runtime::duration::duration_mul as *const ()),
    ("duration_div", crate::runtime::duration::duration_div as *const ()),
    ("duration_lt", crate::runtime::duration::duration_lt as *const ()),
    ("duration_eq", crate::runtime::duration::duration_eq as *const ()),
    ("process_command_new", crate::runtime::process::process_command_new as *const ()),
    ("process_command_arg", crate::runtime::process::process_command_arg as *const ()),
    ("process_command_output", crate::runtime::process::process_command_output as *const ()),
    ("process_command_status", crate::runtime::process::process_command_status as *const ()),
    ("process_output_stdout", crate::runtime::process::process_output_stdout as *const ()),
    ("process_output_stderr", crate::runtime::process::process_output_stderr as *const ()),
    ("process_output_status", crate::runtime::process::process_output_status as *const ()),
    ("thread_spawn", crate::runtime::thread_::thread_spawn as *const ()),
    ("thread_join", crate::runtime::thread_::thread_join as *const ()),
    ("thread_sleep_ms", crate::runtime::thread_::thread_sleep_ms as *const ()),
];

/// Register static LLVM-name → Rust-host mappings for JIT mode.
pub fn register_jit_mappings<'ctx>(module: &Module<'ctx>, ee: &ExecutionEngine<'ctx>) {
    for (name, ptr) in JIT_MAPPINGS {
        if let Some(f) = module.get_function(name) {
            ee.add_global_mapping(&f, *ptr as usize);
        }
    }
}
