// @generated by tools/gen_from_registry.py --emit-core — DO NOT EDIT BY HAND
// Regenerate: python3 tools/gen_from_registry.py --emit-core
// Source of truth: pylib/runtime_core.txt

use inkwell::context::Context;
use inkwell::module::{Linkage, Module};
use inkwell::types::{IntType, PointerType};

/// Declare core runtime externs (map_*/zeta_*/print(ln)_*/array_*).
pub fn declare_core_runtime_fns<'ctx>(
    context: &'ctx Context,
    module: &Module<'ctx>,
    i64_type: IntType<'ctx>,
    ptr_type: PointerType<'ctx>,
) {
    let f64_type = context.f64_type();
    let void_type = context.void_type();

    module.add_function("array_free", void_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("array_get", i64_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("array_len", i64_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("array_new", i64_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("array_push", i64_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("array_set", void_type.fn_type(&[i64_type.into(), i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("array_set_len", void_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("map_free", void_type.fn_type(&[ptr_type.into()], false), Some(Linkage::External));
    module.add_function("map_get", i64_type.fn_type(&[ptr_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("map_insert", void_type.fn_type(&[ptr_type.into(), i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("map_new", ptr_type.fn_type(&[], false), Some(Linkage::External));
    module.add_function("print_bool", void_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("print_f64", void_type.fn_type(&[f64_type.into()], false), Some(Linkage::External));
    module.add_function("print_i64", void_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("print_result", void_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("print_str", void_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("println_f64", void_type.fn_type(&[f64_type.into()], false), Some(Linkage::External));
    module.add_function("println_i64", void_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("println_str", void_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_arange", i64_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_arange_from", i64_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_arange_step", i64_type.fn_type(&[i64_type.into(), i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_array_get_bool", i64_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_array_get_i64", i64_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_array_set_bool", void_type.fn_type(&[i64_type.into(), i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_array_set_i64", void_type.fn_type(&[i64_type.into(), i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_assert_fail", void_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_collect_dict", i64_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_collect_literals", i64_type.fn_type(&[i64_type.into(), i64_type.into(), i64_type.into(), i64_type.into(), i64_type.into(), i64_type.into(), i64_type.into(), i64_type.into()], true), Some(Linkage::External));
    module.add_function("zeta_collect_vec_n", i64_type.fn_type(&[i64_type.into(), i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_diff_n", i64_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_dynarray_new", i64_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_env_get", i64_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_env_set", void_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_float_f64", f64_type.fn_type(&[f64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_float_i64", f64_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_float_str", f64_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_floor_f64", f64_type.fn_type(&[f64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_fmt_f64_spec", i64_type.fn_type(&[f64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_identity1", i64_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_int_f64", i64_type.fn_type(&[f64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_int_i64", i64_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_int_str", i64_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_linspace_i64", i64_type.fn_type(&[i64_type.into(), i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_list", i64_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_log_noop1", void_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_log_noop2", void_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_map_len", i64_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_map_set_tag", void_type.fn_type(&[i64_type.into(), i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_module_decl", i64_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_nonlocal_decl", i64_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_pack_pair", i64_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_param_default", i64_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_platform_obj", i64_type.fn_type(&[i64_type.into(), i64_type.into(), i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_print_i64", void_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_println_i64", void_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_py_from", i64_type.fn_type(&[i64_type.into(), i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_py_import", i64_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_round_f64", i64_type.fn_type(&[f64_type.into(), i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_sieve_new", i64_type.fn_type(&[i64_type.into()], false), Some(Linkage::External));
    module.add_function("zeta_sorted_vec_len", i64_type.fn_type(&[i64_type.into(), i64_type.into()], false), Some(Linkage::External));
}
