#!/usr/bin/env python3
"""tools/gen_from_registry.py — advice.md 任务 A2

从 pylib/registry.txt 生成 codegen 用的声明源，并提供 --check（nm 核对）。

用法:
  python3 tools/gen_from_registry.py --emit     # 写 src/backend/codegen/runtime_decls_registry.rs
  python3 tools/gen_from_registry.py --check    # nm 核对（同 check_registry_symbols.sh）
  python3 tools/gen_from_registry.py --emit --check
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REG = ROOT / "pylib" / "registry.txt"
CORE = ROOT / "pylib" / "runtime_core.txt"
JIT_MAP = ROOT / "pylib" / "jit_mappings.txt"
ALIASES = ROOT / "pylib" / "runtime_aliases.txt"
OUT = ROOT / "src" / "backend" / "codegen" / "runtime_decls_registry.rs"
OUT_CORE = ROOT / "src" / "backend" / "codegen" / "runtime_decls_core.rs"
OUT_JIT = ROOT / "src" / "backend" / "codegen" / "jit_mappings_gen.rs"
OUT_ALIASES = ROOT / "runtime" / "aliases.inc.c"


def parse_registry(text: str):
    """Yield (kind, symbol, args:list[str], ret:str, stub:bool, decl:bool)."""
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        kind = parts[0]
        if kind not in ("F", "W", "X"):
            continue
        stub = any(p == "stub=1" or p.startswith("stub=1") for p in parts)
        # decl defaults true; decl=0 means skip emit
        decl = True
        for p in parts:
            if p.startswith("decl="):
                decl = p.split("=", 1)[1] in ("1", "true", "yes")
        args: list[str] = []
        ret = "i64"
        for p in parts[1:]:
            if p.startswith("args="):
                v = p[5:]
                if v:
                    if kind == "W" and v.isdigit():
                        # W arity including receiver
                        args = ["i64"] * int(v)
                    else:
                        args = [a for a in v.split(",") if a]
            elif p.startswith("ret=") and not p.startswith("ret_handle="):
                ret = p[4:]
        if kind == "F":
            # F module member symbol ...
            if len(parts) < 4:
                continue
            symbol = parts[3]
        elif kind == "W":
            if len(parts) < 4:
                continue
            symbol = parts[3]
            if not args:
                args = ["i64"]  # receiver only
        else:  # X
            if len(parts) < 2:
                continue
            symbol = parts[1]
        yield kind, symbol, args, ret, stub, decl


def collect_decls(text: str) -> list[tuple[str, list[str], str]]:
    seen: dict[str, tuple[list[str], str]] = {}
    for _kind, symbol, args, ret, stub, decl in parse_registry(text):
        if not decl:
            continue
        # stub=1 with decl=1: real abort wrappers (task D); still declare.
        # Match pylib::all_externs: only py_* enter the generated table;
        # zeta_* / map_* stay hand-declared in codegen::new.
        if not symbol.startswith("py_"):
            continue
        seen[symbol] = (args, ret)
    items = sorted(seen.items(), key=lambda x: x[0])
    return [(sym, args, ret) for sym, (args, ret) in items]


def emit_rs(decls: list[tuple[str, list[str], str]]) -> str:
    lines = [
        "// @generated by tools/gen_from_registry.py — DO NOT EDIT BY HAND",
        "// Regenerate: python3 tools/gen_from_registry.py --emit",
        "// Source of truth: pylib/registry.txt (skip decl=0; include stub=1 abort wrappers)",
        "",
        "use inkwell::context::Context;",
        "use inkwell::module::{Linkage, Module};",
        "use inkwell::types::IntType;",
        "",
        "/// Declare Python-compat / registry-backed runtime externs.",
        "pub fn declare_registry_runtime_fns<'ctx>(",
        "    context: &'ctx Context,",
        "    module: &Module<'ctx>,",
        "    i64_type: IntType<'ctx>,",
        ") {",
        "    let f64_type = context.f64_type();",
        "    let void_type = context.void_type();",
        "",
    ]
    for sym, args, ret in decls:
        # Only emit symbols that all_externs historically emitted (py_*), plus
        # any zeta_ registered helpers — keep the full declared set.
        param_exprs = []
        for a in args:
            if a == "f64":
                param_exprs.append("f64_type.into()")
            else:
                param_exprs.append("i64_type.into()")
        params = ", ".join(param_exprs)
        if ret == "void":
            fn_ty = f"void_type.fn_type(&[{params}], false)"
        elif ret == "f64":
            fn_ty = f"f64_type.fn_type(&[{params}], false)"
        else:
            fn_ty = f"i64_type.fn_type(&[{params}], false)"
        lines.append(f'    module.add_function("{sym}", {fn_ty}, Some(Linkage::External));')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def parse_core(text: str) -> list[tuple[str, list[str], str, bool]]:
    """Yield (symbol, args, ret, variadic) from runtime_core.txt."""
    out: list[tuple[str, list[str], str, bool]] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        symbol = parts[0]
        args: list[str] = []
        ret = "i64"
        variadic = False
        for p in parts[1:]:
            if p.startswith("args="):
                v = p[5:]
                args = [a for a in v.split(",") if a] if v else []
            elif p.startswith("ret="):
                ret = p[4:]
            elif p == "variadic=1" or p.startswith("variadic=1"):
                variadic = True
        out.append((symbol, args, ret, variadic))
    out.sort(key=lambda x: x[0])
    return out


def emit_core_rs(decls: list[tuple[str, list[str], str, bool]]) -> str:
    lines = [
        "// @generated by tools/gen_from_registry.py --emit-core — DO NOT EDIT BY HAND",
        "// Regenerate: python3 tools/gen_from_registry.py --emit-core",
        "// Source of truth: pylib/runtime_core.txt",
        "",
        "use inkwell::context::Context;",
        "use inkwell::module::{Linkage, Module};",
        "use inkwell::types::{IntType, PointerType};",
        "",
        "/// Declare core runtime externs (map_*/zeta_*/print(ln)_*/array_*).",
        "pub fn declare_core_runtime_fns<'ctx>(",
        "    context: &'ctx Context,",
        "    module: &Module<'ctx>,",
        "    i64_type: IntType<'ctx>,",
        "    ptr_type: PointerType<'ctx>,",
        ") {",
        "    let f64_type = context.f64_type();",
        "    let void_type = context.void_type();",
        "",
    ]
    for sym, args, ret, variadic in decls:
        param_exprs = []
        for a in args:
            if a == "f64":
                param_exprs.append("f64_type.into()")
            elif a == "ptr":
                param_exprs.append("ptr_type.into()")
            else:
                param_exprs.append("i64_type.into()")
        params = ", ".join(param_exprs)
        var = "true" if variadic else "false"
        if ret == "void":
            fn_ty = f"void_type.fn_type(&[{params}], {var})"
        elif ret == "f64":
            fn_ty = f"f64_type.fn_type(&[{params}], {var})"
        elif ret == "ptr":
            fn_ty = f"ptr_type.fn_type(&[{params}], {var})"
        else:
            fn_ty = f"i64_type.fn_type(&[{params}], {var})"
        lines.append(f'    module.add_function("{sym}", {fn_ty}, Some(Linkage::External));')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def parse_jit_mappings(text: str) -> list[tuple[str, str]]:
    """Yield (llvm_name, rust_path) from jit_mappings.txt."""
    out: list[tuple[str, str]] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        out.append((parts[0], parts[1]))
    return out


def emit_jit_rs(mappings: list[tuple[str, str]]) -> str:
    lines = [
        "// @generated by tools/gen_from_registry.py --emit-jit — DO NOT EDIT BY HAND",
        "// Regenerate: python3 tools/gen_from_registry.py --emit-jit",
        "// Source of truth: pylib/jit_mappings.txt",
        "",
        "use inkwell::execution_engine::ExecutionEngine;",
        "use inkwell::module::Module;",
        "",
        "/// Every LLVM name that JIT mode resolves to a Rust host function.",
        "///",
        "/// This is also the *authority* for the `--jit` preflight diagnostic: outside of",
        "/// these names and the `vec_*` monomorphs, an external only resolves if the",
        "/// compiler process itself already exports it — see `jit.rs::jit_symbol_resolvable`.",
        "///",
        "/// Host entries stay `*const ()`: a pointer has no integer value in const eval, so",
        "/// the cast to the address `add_global_mapping` wants happens at run time.",
        "pub const JIT_MAPPINGS: &[(&str, *const ())] = &[",
    ]
    for llvm_name, rust_path in mappings:
        lines.append(f'    ("{llvm_name}", {rust_path} as *const ()),')
    lines.append("];")
    lines.append("")
    lines.append("/// Register static LLVM-name → Rust-host mappings for JIT mode.")
    lines.append("pub fn register_jit_mappings<'ctx>(module: &Module<'ctx>, ee: &ExecutionEngine<'ctx>) {")
    lines.append("    for (name, ptr) in JIT_MAPPINGS {")
    lines.append("        if let Some(f) = module.get_function(name) {")
    lines.append("            ee.add_global_mapping(&f, *ptr as usize);")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def nm_defined(objs: list[Path]) -> set[str]:
    out: set[str] = set()
    for o in objs:
        if not o.is_file():
            continue
        r = subprocess.run(["nm", "-gU", str(o)], capture_output=True, text=True)
        for line in r.stdout.splitlines():
            parts = line.split()
            if len(parts) >= 3 and parts[1] in ("T", "D", "B"):
                s = parts[-1]
                if s.startswith("_"):
                    s = s[1:]
                out.add(s)
    return out


def check(text: str) -> int:
    wanted = []
    for _k, sym, _a, _r, stub, decl in parse_registry(text):
        if not decl:
            continue
        wanted.append(sym)
    wanted = sorted(set(wanted))
    defined = nm_defined([ROOT / "zeta_runtime_c.o", ROOT / "tokio_runtime.o"])
    missing = [s for s in wanted if s not in defined]
    for s in missing:
        print(f"MISSING {s}")
    if missing:
        print(f"gen_from_registry --check: {len(missing)} missing", file=sys.stderr)
        return 1
    return 0


def emit_aliases_inc(path: Path) -> str:
    lines = [
        "/* @generated by tools/gen_from_registry.py --emit-aliases — DO NOT EDIT */",
        "/* Source: pylib/runtime_aliases.txt */",
        "__asm__(",
    ]
    pairs = []
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        alias, target = parts[0], parts[1]
        pairs.append((alias, target))
        lines.append(
            f'    ".globl _{alias}\\n\\t.set _{alias}, _{target}\\n"'
        )
    lines.append(");")
    lines.append("")
    return "\n".join(lines), len(pairs)


def scan_pylib_stubs() -> list[str]:
    """D4: `# stub: <name>` / `// stub: <name>` in pylib/*.z."""
    out: list[str] = []
    pylib = ROOT / "pylib"
    for path in sorted(pylib.glob("*.z")):
        for raw in path.read_text().splitlines():
            line = raw.strip()
            if line.startswith("# stub:"):
                name = line[len("# stub:") :].strip()
            elif line.startswith("// stub:"):
                name = line[len("// stub:") :].strip()
            else:
                continue
            if name:
                out.append(name)
    return sorted(set(out))


def list_stubs(text: str) -> int:
    """Print registry stub=1 ∪ pylib `# stub:` (same set as `zetac --list-stubs`)."""
    reg = []
    for _k, sym, _a, _r, stub, _d in parse_registry(text):
        if stub:
            reg.append(sym)
    reg = sorted(set(reg))
    files = scan_pylib_stubs()
    all_ = sorted(set(reg) | set(files))
    print(f"Zeta stubs ({len(all_)} = registry {len(reg)} + pylib {len(files)}):")
    for s in all_:
        print(f"  {s}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", action="store_true", help="emit runtime_decls_registry.rs")
    ap.add_argument("--emit-core", action="store_true", help="emit runtime_decls_core.rs")
    ap.add_argument("--emit-jit", action="store_true", help="emit jit_mappings_gen.rs")
    ap.add_argument("--emit-aliases", action="store_true", help="emit runtime/aliases.inc.c")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--list", action="store_true", help="D4: list registry+pylib stubs")
    args = ap.parse_args()
    if not any(
        [
            args.emit,
            args.check,
            args.emit_aliases,
            args.emit_core,
            args.emit_jit,
            args.list,
        ]
    ):
        ap.print_help()
        return 2
    text = REG.read_text()
    if args.list:
        return list_stubs(text)
    rc = 0
    if args.emit:
        decls = collect_decls(text)
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(emit_rs(decls))
        print(f"wrote {OUT} ({len(decls)} symbols)", file=sys.stderr)
    if args.emit_core:
        core = parse_core(CORE.read_text())
        OUT_CORE.parent.mkdir(parents=True, exist_ok=True)
        OUT_CORE.write_text(emit_core_rs(core))
        print(f"wrote {OUT_CORE} ({len(core)} symbols)", file=sys.stderr)
    if args.emit_jit:
        maps = parse_jit_mappings(JIT_MAP.read_text())
        OUT_JIT.parent.mkdir(parents=True, exist_ok=True)
        OUT_JIT.write_text(emit_jit_rs(maps))
        print(f"wrote {OUT_JIT} ({len(maps)} mappings)", file=sys.stderr)
    if args.emit_aliases:
        body, n = emit_aliases_inc(ALIASES)
        OUT_ALIASES.write_text(body)
        print(f"wrote {OUT_ALIASES} ({n} aliases)", file=sys.stderr)
    if args.check:
        rc = check(text)
    return rc


if __name__ == "__main__":
    sys.exit(main())
